# SPDX-FileCopyrightText: Copyright © 2024 - 2025 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

name: node
on: [push, workflow_call]
jobs:
  format:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - &checkout-step
        uses: actions/checkout@v6.0.0
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          filter: "blob:none"
          fetch-depth: 0
      - &setup-node1
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
          package-manager-cache: false
      - &setup-corepack
        run: corepack enable
      - &setup-node2
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
          cache: "yarn"
      - &yarn-install
        run: yarn install --immutable --inline-builds --check-resolutions
      - run: yarn exec prettier --ignore-unknown --check '**'
  eslint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - *checkout-step
      - *setup-node1
      - *setup-corepack
      - *setup-node2
      - *yarn-install
      - run: yarn why eslint --peers
      - run: yarn exec eslint --env-info
      - run: yarn exec eslint
